### PR TITLE
allow to also unsubscribe handlers

### PR DESCRIPTION
**Pull request by yanick**

### CODE REVIEW

**Comment by debug-ito** [comment]
Thanks for contribution! The implementation looks perfect to me.
I'll add some tests and documentation before releasing.

@plicease This p-r allows users to drop (unregister) callbacks from Plack::App::Connection objects. It may be a good idea for AnyEvent::WebSocket::Connection to have the same functionality. If you are not interested, it's ok :)

**Comment by plicease** [comment]
I am happy to accept a PR I probably won't have time to work on it myself atm.

**Comment by yanick** [comment]
PR done. :-)

**Comment by debug-ito** [comment]
released as version 0.06.

**Pull request merged**
